defmodule Nominator.Repo.Migrations.CreateFamilies do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:swimmers, primary_key: false) do
      add :family_id,
          references(:families, column: :id, name: "swimmers_family_id_fkey", type: :uuid),
          null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :group, :text
      add :name, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:families, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :family_token, :uuid
      add :email, :text, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create unique_index(:families, [:family_token], name: "families_unique_family_token_index")

    create unique_index(:families, [:email], name: "families_unique_name_index")
  end

  def down do
    drop_if_exists unique_index(:families, [:email], name: "families_unique_name_index")

    drop_if_exists unique_index(:families, [:family_token],
                     name: "families_unique_family_token_index"
                   )

    drop table(:families)

    raise "SQLite does not support dropping foreign key constraints. " <>
            "You will need to manually recreate the `swimmers` table without the `swimmers_family_id_fkey` constraint. " <>
            "See https://www.techonthenet.com/sqlite/foreign_keys/drop.php for guidance."

    drop table(:swimmers)
  end
end
