defmodule Nominator.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:votes, [:voter_id], name: "votes_one_vote_per_voter_index")
  end

  def down do
    drop_if_exists unique_index(:votes, [:voter_id], name: "votes_one_vote_per_voter_index")
  end
end
