defmodule Nominator.Repo.Migrations.AddVoteRelationships do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:voting_settings, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :closed_at, :utc_datetime
      add :is_open, :bigint, null: false
      add :id, :uuid, null: false, primary_key: true
    end

    create table(:votes, primary_key: false) do
      add :candidate_id,
          references(:swimmers, column: :id, name: "votes_candidate_id_fkey", type: :uuid),
          null: false

      add :voter_id, references(:swimmers, column: :id, name: "votes_voter_id_fkey", type: :uuid),
        null: false

      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:votes)

    drop table(:voting_settings)
  end
end
